# Pacman
alias pac='sudo pacman -S'  
alias pacu='sudo pacman -Syu'    
alias pacr='sudo pacman -Rs'   
alias pacs='pacman -Ss'      
alias paci='pacman -Si'      
alias paclo='pacman -Qdt'    
alias pacro='paclo && sudo pacman -Rns $(pacman -Qtdq)' 
alias pacc='sudo pacman -Scc'    
alias paclf='pacman -Ql'   
